#!/usr/bin/env python3
"""Data Report Generator - renders business data into a styled HTML report.

Usage:
    python generate_report.py --data report_data.json --output report.html

Input JSON schema:
{
  "title": "报告标题",
  "subtitle": "副标题/时间范围",
  "footer": "页脚说明",
  "kpis": [
    {"label": "指标名", "value": "数值", "trend": "+12%", "direction": "up|down|flat"}
  ],
  "charts": [
    {"type": "bar|line|pie|doughnut", "title": "图表标题",
     "labels": ["a","b"], "datasets": [{"label": "系列", "data": [1,2]}]}
  ],
  "tables": [
    {"title": "表格标题", "columns": ["列1","列2"],
     "rows": [["v1","v2"], ["v3","v4"]],
     "badge_columns": {"列名": {"值": "blue|green|orange|red"}}}
  ]
}
"""
import argparse, json, os, sys

TEMPLATE_PATH = os.path.join(os.path.dirname(__file__), "..", "assets", "report-template.html")
PALETTE = ["#1a56db", "#0ea5e9", "#10b981", "#f59e0b", "#ef4444", "#8b5cf6", "#14b8a6", "#f97316"]


def esc(s):
    return str(s).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def render_kpis(kpis):
    out = []
    for k in kpis:
        d = k.get("direction", "flat")
        arrow = {"up": "\u2191", "down": "\u2193"}.get(d, "\u2192")
        trend = k.get("trend", "")
        trend_html = f'<div class="trend {d}">{arrow} {esc(trend)}</div>' if trend else ""
        out.append(
            f'<div class="kpi-card"><div class="label">{esc(k["label"])}</div>'
            f'<div class="value">{esc(k["value"])}</div>{trend_html}</div>'
        )
    return "\n".join(out)


def render_charts(charts):
    sections, scripts = [], []
    for i, c in enumerate(charts):
        cid = f"chart{i}"
        sections.append(
            f'<div class="card"><div class="section-title">{esc(c["title"])}</div>'
            f'<div style="position:relative;height:320px"><canvas id="{cid}"></canvas></div></div>'
        )
        datasets = []
        for j, ds in enumerate(c["datasets"]):
            color = PALETTE[j % len(PALETTE)]
            if c["type"] in ("pie", "doughnut"):
                colors = PALETTE[: len(ds["data"])]
                datasets.append({"label": ds.get("label", ""), "data": ds["data"], "backgroundColor": colors})
            else:
                datasets.append({"label": ds.get("label", ""), "data": ds["data"],
                                 "backgroundColor": color, "borderColor": color, "tension": 0.3})
        cfg = {"type": c["type"],
               "data": {"labels": c["labels"], "datasets": datasets},
               "options": {"responsive": True, "maintainAspectRatio": False}}
        scripts.append(f"new Chart(document.getElementById('{cid}'), {json.dumps(cfg, ensure_ascii=False)});")
    return "\n".join(sections), "\n".join(scripts)


def render_tables(tables):
    out = []
    for t in tables:
        cols = t["columns"]
        ths = "".join(f"<th>{esc(c)}</th>" for c in cols)
        rows_html = []
        for row in t["rows"]:
            tds = []
            for ci, cell in enumerate(row):
                col_name = cols[ci] if ci < len(cols) else ""
                badge_map = t.get("badge_columns", {}).get(col_name, {})
                if col_name in t.get("badge_columns", {}) and str(cell) in badge_map:
                    tds.append(f'<td><span class="badge {badge_map[str(cell)]}">{esc(cell)}</span></td>')
                else:
                    tds.append(f"<td>{esc(cell)}</td>")
            rows_html.append("<tr>" + "".join(tds) + "</tr>")
        out.append(
            f'<div class="card"><div class="section-title">{esc(t["title"])}</div>'
            f'<table><thead><tr>{ths}</tr></thead><tbody>{"".join(rows_html)}</tbody></table></div>'
        )
    return "\n".join(out)


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--data", required=True, help="Input JSON data file")
    p.add_argument("--output", required=True, help="Output HTML file")
    p.add_argument("--template", default=TEMPLATE_PATH, help="HTML template path")
    args = p.parse_args()

    with open(args.data, encoding="utf-8") as f:
        data = json.load(f)
    with open(args.template, encoding="utf-8") as f:
        tpl = f.read()

    chart_sections, chart_scripts = render_charts(data.get("charts", []))
    html = (tpl.replace("{{REPORT_TITLE}}", esc(data.get("title", "数据报告")))
               .replace("{{REPORT_SUBTITLE}}", esc(data.get("subtitle", "")))
               .replace("{{KPI_CARDS}}", render_kpis(data.get("kpis", [])))
               .replace("{{CHART_SECTIONS}}", chart_sections)
               .replace("{{TABLE_SECTIONS}}", render_tables(data.get("tables", [])))
               .replace("{{FOOTER_TEXT}}", esc(data.get("footer", "Generated by data-report skill")))
               .replace("{{CHART_SCRIPTS}}", chart_scripts))

    with open(args.output, "w", encoding="utf-8") as f:
        f.write(html)
    print(f"OK Report generated: {args.output} ({os.path.getsize(args.output)} bytes)")


if __name__ == "__main__":
    main()
